name: thirdfloor
favicon: null
layout_spectrum: 0.2358048448804766
typography_spectrum: 0.6736746900714934
title: Webdesign Eindhoven
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8600035815034062
  lightness: 0.9789740084670484
  saturation: 0.020519254030659795
  rhythmicContrast: 0.01223095366731286
purpose: []
